# Generated by stoatworks-unraid/scripts/gen-docker.mjs from fleet.json.
# Repo: RFutils. Edit fleet.json and regenerate — direct edits are overwritten.
#
# RFutils — Node service.
#
# NOTE: Discovers receivers over the LAN, so the template ships host networking.
# Port is read from RFUTILS_SERVER_PORT (falling back to PORT, then 8420).

FROM node:22-slim AS builder
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

FROM node:22-slim
WORKDIR /app
ENV NODE_ENV=production
ENV RFUTILS_SERVER_PORT=8420

# The whole built tree is copied, node_modules included. These are npm
# workspaces: pruning to production dependencies means re-resolving the
# workspace graph in the runtime stage, and getting that subtly wrong yields an
# image that starts and then throws MODULE_NOT_FOUND on the first request to
# whichever route needed the pruned package. Size is the price of not doing that.
COPY --from=builder /app ./

EXPOSE 8420

# A TCP connect, not an HTTP request against a guessed path. If this app grows a
# /health route the check can be tightened; asserting one that does not exist
# would mark a working container unhealthy forever.
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
    CMD node -e "require('net').connect(8420,'127.0.0.1').on('connect',()=>process.exit(0)).on('error',()=>process.exit(1))" || exit 1

CMD ["node", "packages/server/dist/index.js"]
